name: build and deploy yuurei
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - name: compile with grunt
        uses: elstudio/actions-js-build/build@v2

      - name: deploy yuurei
        uses: TryGhost/action-deploy-theme@v1.2.0
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
          exclude: "gulpfile.js package-lock.json *node_modules/* *assets/css/* *assets/js/* *assets/ghostHunter/*"
